### ISSUE TITLE
Documentation for use with Button API would be helpful

### ISSUE THREAD

**Issue by smlarkin** [BetterTheWorld/react-native-button-sdk#1]
This package looks to be a great help for anyone that needs to use Button in RN. And it would be nice to have some pointers / examples / directions on how to use it.

**Comment by codybrouwers** [comment]
Hey @smlarkin thanks for the suggestion! You're definitely right, I will get around to adding some documentation this week.

Are you using the package? I recently had to setup the Button SDK on my company's React Native app so I decided to open source the work but wasn't sure if anyone else would be interested in using it.

**Comment by codybrouwers** [comment]
Hey @smlarkin I've updated the README, let me know if its missing anything and thanks again for the suggestion!

**Comment by smlarkin** [comment]
Hi Cody,

Are you getting my email replies?

I am SO HAPPY you setup a Button API example for RN.

I need to actually work with the Button Team on a few things.  Maybe, we can team up to get it to be “official” —ish?

Cheers,

Shawn

**Comment by codybrouwers** [comment]
Hey @smlarkin that's great to here and yea for sure we can definitely work together on it!

There are a bunch of things that the native Button SDK does that I haven't included yet because we aren't using those parts yet at my company.

What do you think should be added to make it more official?

**Comment by smlarkin** [comment]
Hey Cody,

I sent this same email under the subject "React Native Buton SDK :)” because I thought I had lost this email … but I just found it.  So reply to either when you have time … If you prefer, I’m happy to communicate with you through GH issues or, really, however you prefer going forward.  Let me know :)

Regarding, Button support, I’ve actually pointed them to your repo to see if they would be willing to help out for any implementation issues.  Is that okay?

Finally, is there any way you can tell me the purpose of the method...

// Open the browser with a non-Button merchant URL
ButtonSDK.openURL({
  url:      "https://www.google.com <https://www.google.com/>",
  title:    "My Browser Title",
  subtitle: "My Browser Subtitle"
});


…I must be missing something … I thought you basically need to send button the info you provide in this method...

// Fetch a purchase path from Button and start the browser
ButtonSDK.startPurchasePath({
  url:                   "https://the.button.url <https://the.button.url/>",
  token:                 "my-tracking-token",
  headerTitle:           "My Button Browser Title",
  headerSubtitle:        "My Button Browser Subtitle",
  headerTitleColor:      "#FFFFF",
  headerSubtitleColor:   "#FFFFF",
  headerBackgroundColor: "#FFFFF",
  headerTintColor:       "#FFFFF",
  footerBackgroundColor: "#FFFFF",
  footerTintColor:       "#FFFFF"
});

…so what it the purpose of opening the browser with a non-Button merchant url ?

I have a couple more questions, but I’ll wait to see how you prefer to chat :)

Also, I’m in Montreal … are you Toronto ?

Cheers!

Shawn
